# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Supabase < Formula
  desc "Supabase CLI"
  homepage "https://supabase.io"
  version "0.10.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/soedirgo/cli/releases/download/v0.10.8/supabase_0.10.8_darwin_arm64.tar.gz"
      sha256 "031ac9ec73e96c7c8020040dfe735917689178a86489d275c914998777388a5e"

      def install
        bin.install "supabase"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/soedirgo/cli/releases/download/v0.10.8/supabase_0.10.8_darwin_amd64.tar.gz"
      sha256 "f671926f306ade3eebbdfbfb868a5a3b35aaf302f6a61465609c486800aa91ee"

      def install
        bin.install "supabase"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/soedirgo/cli/releases/download/v0.10.8/supabase_0.10.8_linux_amd64.tar.gz"
      sha256 "b8930cd3bb6d71c864ecc2071e3356b7c4041fd2b901013046933adc193e43ba"

      def install
        bin.install "supabase"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/soedirgo/cli/releases/download/v0.10.8/supabase_0.10.8_linux_arm64.tar.gz"
      sha256 "fe2f49c866a52daa78637e37b2d66cfb8f42964523585802fa296223bfaa244f"

      def install
        bin.install "supabase"
      end
    end
  end
end
