# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Supabase < Formula
  desc "Supabase CLI"
  homepage "https://supabase.io"
  version "0.10.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/soedirgo/cli/releases/download/v0.10.9/supabase_0.10.9_darwin_arm64.tar.gz"
      sha256 "97011b66d6c18e25d471f5e99b35db6ae00213c24eb11858792979274e47d1cd"

      def install
        bin.install "supabase"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/soedirgo/cli/releases/download/v0.10.9/supabase_0.10.9_darwin_amd64.tar.gz"
      sha256 "713ad6b3df95b6b699c09aaeca96b0d2777618a14edcf62498dda2cfcfddd0cd"

      def install
        bin.install "supabase"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/soedirgo/cli/releases/download/v0.10.9/supabase_0.10.9_linux_amd64.tar.gz"
      sha256 "c5d67585a780c53d826ce4a7d5ffa387d14bef0a79cb74b16f0cfbc5c897ba02"

      def install
        bin.install "supabase"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/soedirgo/cli/releases/download/v0.10.9/supabase_0.10.9_linux_arm64.tar.gz"
      sha256 "de3aa3793e759003407d25228c0745d27dd14ae7ba41744aa252389c216a968d"

      def install
        bin.install "supabase"
      end
    end
  end
end
