# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Supabase < Formula
  desc "Supabase CLI"
  homepage "https://supabase.io"
  version "0.10.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/soedirgo/cli/releases/download/v0.10.7/supabase_0.10.7_darwin_arm64.tar.gz"
      sha256 "8413ed7a6b090d5cd4b94dec24de33433ed564daea6819a5835c3b967b27c2e9"

      def install
        bin.install "supabase"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/soedirgo/cli/releases/download/v0.10.7/supabase_0.10.7_darwin_amd64.tar.gz"
      sha256 "1d3326ef55f6072e96e5984043269352052765b648bb2396cbd0b11f6e40089e"

      def install
        bin.install "supabase"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/soedirgo/cli/releases/download/v0.10.7/supabase_0.10.7_linux_amd64.tar.gz"
      sha256 "9cdee2d27eb39d66e005c50edc31e0ed75c0a036ca6912c1d9ae77390666019e"

      def install
        bin.install "supabase"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/soedirgo/cli/releases/download/v0.10.7/supabase_0.10.7_linux_arm64.tar.gz"
      sha256 "b16d868d265a0cbcb851835e3dd2e14685f40a92ce434a3d3fe7b87ea6eb1869"

      def install
        bin.install "supabase"
      end
    end
  end
end
